-- ============================================================
-- SAD Web — schema.sql
-- Documentação fiel do banco de produção (projeto sad-app, okdghwjcpnkkxcrvjaxg)
-- Gerada por introspecção real do banco em 2026-09-16.
-- Padrão de RLS: SELECT liberado para authenticated; INSERT/UPDATE/DELETE via pode_escrever()
-- (exceto perfis, que tem regra própria de admin/self).
-- alvara_contador e protocolo_contador não têm policies de RLS observadas no banco —
-- são contadores internos, aparentemente não acessados direto via REST pelo frontend.
-- ============================================================

-- ============================================================
-- FUNÇÕES DE CONTROLE DE ACESSO
-- ============================================================

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select exists (
    select 1 from public.perfis
    where lower(email) = lower(auth.jwt() ->> 'email')
      and papel = 'admin'
  );
$$;

create or replace function public.pode_escrever()
returns boolean
language sql
stable
as $$
  select exists (
    select 1 from public.perfis
    where lower(email) = lower(auth.jwt() ->> 'email')
      and papel in ('admin','completo')
  );
$$;

-- ============================================================
-- PERFIS (controle de acesso dos usuários)
-- ============================================================
create table if not exists perfis (
  email text primary key,
  papel text not null default 'leitura',
  criado_em timestamptz not null default now()
);

alter table perfis enable row level security;
create policy perfis_select on perfis for select to authenticated
  using (lower(email) = lower(auth.jwt() ->> 'email') or is_admin());
create policy perfis_insert on perfis for insert to authenticated
  with check ((lower(email) = lower(auth.jwt() ->> 'email') and papel = 'leitura') or is_admin());
create policy perfis_update on perfis for update to authenticated
  using (is_admin()) with check (is_admin());
create policy perfis_delete on perfis for delete to authenticated
  using (is_admin());

-- ============================================================
-- PESSOAS / DOSSIÊS
-- ============================================================
create table if not exists pessoas (
  id bigint generated by default as identity primary key,
  nome text not null,
  cpf text default '',
  telefone text default '',
  endereco text default '',
  email text default '',
  orgao text default '',
  observacoes text default '',
  status_ocorrencia text default 'em_aberto'
    check (status_ocorrencia in ('em_aberto','em_andamento','concluido','arquivado')),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  rg text,
  data_nascimento text,
  genero text,
  estado_civil text,
  bairro text,
  municipio text,
  cep text,
  ponto_referencia text,
  gps_lat numeric,
  gps_lng numeric,
  num_pessoas_familia integer,
  renda_familiar text,
  programa_social text,
  tipo_moradia text,
  material_construcao text,
  area_risco boolean,
  deficiencia text,
  doenca_cronica text,
  prioridade text
);

alter table pessoas enable row level security;
create policy pessoas_select on pessoas for select to authenticated using (true);
create policy pessoas_insert on pessoas for insert to authenticated with check (pode_escrever());
create policy pessoas_update on pessoas for update to authenticated using (pode_escrever()) with check (pode_escrever());
create policy pessoas_delete on pessoas for delete to authenticated using (pode_escrever());

-- ============================================================
-- PROTOCOLOS
-- ============================================================
create table if not exists protocolo_contador (
  ano integer primary key,
  ultimo_numero integer not null default 0
);

create table if not exists protocolos (
  id bigint generated by default as identity primary key,
  pessoa_id bigint references pessoas(id) on delete cascade,
  numero text not null,
  assunto text not null,
  descricao text default '',
  data_entrada date,
  prazo date,
  status text default 'aberto'
    check (status in ('aberto','em_andamento','concluido','arquivado')),
  historico jsonb default '[]'::jsonb,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

alter table protocolos enable row level security;
create policy protocolos_select on protocolos for select to authenticated using (true);
create policy protocolos_insert on protocolos for insert to authenticated with check (pode_escrever());
create policy protocolos_update on protocolos for update to authenticated using (pode_escrever()) with check (pode_escrever());
create policy protocolos_delete on protocolos for delete to authenticated using (pode_escrever());

-- ============================================================
-- ENCAMINHAMENTOS (ligados a um protocolo)
-- ============================================================
create table if not exists encaminhamentos (
  id bigint generated by default as identity primary key,
  protocolo_id bigint not null references protocolos(id) on delete cascade,
  orgao text not null,
  data_envio date not null,
  descricao text,
  status text not null default 'pendente',
  retorno text,
  data_retorno date,
  criado_em timestamptz not null default now()
);

alter table encaminhamentos enable row level security;
create policy encaminhamentos_select on encaminhamentos for select to authenticated using (true);
create policy encaminhamentos_insert on encaminhamentos for insert to authenticated with check (pode_escrever());
create policy encaminhamentos_update on encaminhamentos for update to authenticated using (pode_escrever()) with check (pode_escrever());
create policy encaminhamentos_delete on encaminhamentos for delete to authenticated using (pode_escrever());

-- ============================================================
-- DOCUMENTOS RECEBIDOS / GERADOS
-- ============================================================
create table if not exists documentos_recebidos (
  id bigint generated by default as identity primary key,
  pessoa_id bigint references pessoas(id) on delete cascade,
  protocolo_id bigint references protocolos(id) on delete set null,
  nome text not null,
  tipo text default '',
  caminho text default '',
  descricao text default '',
  data_recebimento date,
  criado_em timestamptz not null default now()
);

alter table documentos_recebidos enable row level security;
create policy documentos_recebidos_select on documentos_recebidos for select to authenticated using (true);
create policy documentos_recebidos_insert on documentos_recebidos for insert to authenticated with check (pode_escrever());
create policy documentos_recebidos_update on documentos_recebidos for update to authenticated using (pode_escrever()) with check (pode_escrever());
create policy documentos_recebidos_delete on documentos_recebidos for delete to authenticated using (pode_escrever());

create table if not exists documentos_gerados (
  id bigint generated by default as identity primary key,
  pessoa_id bigint references pessoas(id) on delete cascade,
  protocolo_id bigint references protocolos(id) on delete set null,
  tipo text default 'Ofício',
  titulo text not null,
  conteudo text default '',
  caminho text,
  data_geracao timestamptz default now(),
  criado_em timestamptz not null default now()
);

alter table documentos_gerados enable row level security;
create policy documentos_gerados_select on documentos_gerados for select to authenticated using (true);
create policy documentos_gerados_insert on documentos_gerados for insert to authenticated with check (pode_escrever());
create policy documentos_gerados_update on documentos_gerados for update to authenticated using (pode_escrever()) with check (pode_escrever());
create policy documentos_gerados_delete on documentos_gerados for delete to authenticated using (pode_escrever());

-- ============================================================
-- TAREFAS
-- ============================================================
create table if not exists tarefas (
  id bigint generated by default as identity primary key,
  titulo text not null,
  descricao text default '',
  prioridade text default 'media' check (prioridade in ('baixa','media','alta')),
  prazo date,
  status text default 'pendente' check (status in ('pendente','em_andamento','concluida','arquivada')),
  pessoa_id bigint references pessoas(id) on delete set null,
  protocolo_id bigint references protocolos(id) on delete set null,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

alter table tarefas enable row level security;
create policy tarefas_select on tarefas for select to authenticated using (true);
create policy tarefas_insert on tarefas for insert to authenticated with check (pode_escrever());
create policy tarefas_update on tarefas for update to authenticated using (pode_escrever()) with check (pode_escrever());
create policy tarefas_delete on tarefas for delete to authenticated using (pode_escrever());

-- ============================================================
-- AGENDA
-- ============================================================
create table if not exists agenda (
  id bigint generated by default as identity primary key,
  titulo text not null,
  descricao text default '',
  data date not null,
  horario text default '',
  pessoa_id bigint references pessoas(id) on delete set null,
  protocolo_id bigint references protocolos(id) on delete set null,
  realizado smallint default 0,
  criado_em timestamptz not null default now()
);

alter table agenda enable row level security;
create policy agenda_select on agenda for select to authenticated using (true);
create policy agenda_insert on agenda for insert to authenticated with check (pode_escrever());
create policy agenda_update on agenda for update to authenticated using (pode_escrever()) with check (pode_escrever());
create policy agenda_delete on agenda for delete to authenticated using (pode_escrever());

-- ============================================================
-- CONFIGURAÇÕES
-- ============================================================
create table if not exists configuracoes (
  id bigint generated by default as identity primary key,
  chave text not null unique,
  valor text default ''
);

alter table configuracoes enable row level security;
create policy configuracoes_select on configuracoes for select to authenticated using (true);
create policy configuracoes_insert on configuracoes for insert to authenticated with check (pode_escrever());
create policy configuracoes_update on configuracoes for update to authenticated using (pode_escrever()) with check (pode_escrever());
create policy configuracoes_delete on configuracoes for delete to authenticated using (pode_escrever());

-- ============================================================
-- ALVARÁS
-- ============================================================
create table if not exists alvara_contador (
  ano integer primary key,
  ultimo_numero integer not null default 0
);

create table if not exists alvaras (
  id bigint generated by default as identity primary key,
  numero text unique,
  nome_estabelecimento text not null,
  cnpj text,
  nome_responsavel text,
  cpf_responsavel text,
  telefone text,
  endereco text,
  bairro text,
  municipio text default 'Tefé/AM',
  gps_lat double precision,
  gps_lng double precision,
  tipo_estabelecimento text,
  area_total numeric,
  capacidade_pessoas integer,
  classificacao_porte text,
  possui_extintor boolean,
  qtd_extintores integer,
  tipo_extintor text,
  extintor_validade boolean,
  extintor_localizacao_ok boolean,
  sinalizacao_emergencia boolean,
  saida_desobstruida boolean,
  qtd_saidas integer,
  rotas_fuga_ok boolean,
  instalacao_irregular boolean,
  possui_glp boolean,
  glp_armazenamento_ok boolean,
  sistema_fixo_incendio boolean,
  qual_sistema_fixo text,
  iluminacao_emergencia boolean,
  obs_iluminacao text,
  hidrante_reserva boolean,
  obs_hidrante text,
  planta_baixa boolean,
  obs_planta_baixa text,
  apto_alvara boolean,
  necessita_adequacoes boolean,
  observacoes text,
  descricao_tecnica text,
  situacao_imovel text,
  reavaliacao boolean default false,
  orgao_destino text,
  qual_orgao_outro text,
  nome_vistoriador text,
  matricula_vistoriador text,
  pessoa_id bigint references pessoas(id),
  sentinela_id text unique,
  documento_url text,
  data_vistoria date,
  validade_vistoria date,
  criado_em timestamptz default now(),
  atualizado_em timestamptz default now(),
  relatorio_url text
);

alter table alvaras enable row level security;
create policy alvaras_select on alvaras for select to authenticated using (true);
create policy alvaras_insert on alvaras for insert to authenticated with check (pode_escrever());
create policy alvaras_update on alvaras for update to authenticated using (pode_escrever()) with check (pode_escrever());
create policy alvaras_delete on alvaras for delete to authenticated using (pode_escrever());

create table if not exists alvara_anexos (
  id bigint generated by default as identity primary key,
  alvara_id bigint not null references alvaras(id) on delete cascade,
  nome text not null,
  url text not null,
  criado_em timestamptz not null default now()
);

alter table alvara_anexos enable row level security;
create policy alvara_anexos_select on alvara_anexos for select to authenticated using (true);
create policy alvara_anexos_insert on alvara_anexos for insert to authenticated with check (pode_escrever());
create policy alvara_anexos_update on alvara_anexos for update to authenticated using (pode_escrever()) with check (pode_escrever());
create policy alvara_anexos_delete on alvara_anexos for delete to authenticated using (pode_escrever());

-- ============================================================
-- COMUNIDADES
-- ============================================================
create table if not exists comunidades (
  id bigint generated by default as identity primary key,
  nome text not null,
  gps_lat double precision,
  gps_lng double precision,
  distancia text,
  gasto_combustivel text,
  tipo_motor text,
  duracao_viagem text,
  qtd_pessoas integer,
  presidente_nome text,
  presidente_telefone text,
  presidente_cpf text,
  observacoes text,
  criado_em timestamptz not null default now(),
  qtd_familias integer
);

alter table comunidades enable row level security;
create policy comunidades_select on comunidades for select to authenticated using (true);
create policy comunidades_insert on comunidades for insert to authenticated with check (pode_escrever());
create policy comunidades_update on comunidades for update to authenticated using (pode_escrever()) with check (pode_escrever());
create policy comunidades_delete on comunidades for delete to authenticated using (pode_escrever());

create table if not exists comunidade_anexos (
  id bigint generated by default as identity primary key,
  comunidade_id bigint not null references comunidades(id) on delete cascade,
  nome text not null,
  url text not null,
  criado_em timestamptz not null default now()
);

alter table comunidade_anexos enable row level security;
create policy comunidade_anexos_select on comunidade_anexos for select to authenticated using (true);
create policy comunidade_anexos_insert on comunidade_anexos for insert to authenticated with check (pode_escrever());
create policy comunidade_anexos_update on comunidade_anexos for update to authenticated using (pode_escrever()) with check (pode_escrever());
create policy comunidade_anexos_delete on comunidade_anexos for delete to authenticated using (pode_escrever());

-- ============================================================
-- OCORRÊNCIAS (Mapa de Ocorrências / integração Sentinela DC v2)
-- ============================================================
create table if not exists ocorrencias (
  id uuid primary key default gen_random_uuid(),
  pessoa_id bigint references pessoas(id) on delete set null,
  documento_id uuid,
  documento_url text,
  protocolo text,
  origem text not null default 'sentinela_v2',
  sentinela_id text unique,
  latitude double precision,
  longitude double precision,
  endereco text,
  bairro text,
  municipio_uf text default 'Tefé/AM',
  ponto_referencia text,
  data_vistoria date,
  tipificacao text,
  tipificacao_outro text,
  nivel_risco text,
  localizacao text,
  tipo_imovel text,
  material_construcao text,
  propriedade text,
  pessoas_afetadas integer default 0,
  familias_afetadas integer default 0,
  descricao_situacao text,
  recomendacoes text,
  tipo_estrutura text,
  risco_estrutural text,
  obs_risco_estrutural text,
  risco_hidrologico text,
  orgao_destino text,
  situacao_imovel text,
  reavaliacao boolean default false,
  vistoriador_nome text,
  vistoriador_matricula text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table ocorrencias enable row level security;
create policy ocorrencias_select on ocorrencias for select to authenticated using (true);
create policy ocorrencias_insert on ocorrencias for insert to authenticated with check (pode_escrever());
create policy ocorrencias_update on ocorrencias for update to authenticated using (pode_escrever()) with check (pode_escrever());
create policy ocorrencias_delete on ocorrencias for delete to authenticated using (pode_escrever());

-- ============================================================
-- MONITORAMENTO AMBIENTAL — ESTAÇÕES
-- ============================================================
create table if not exists estacoes_monitoramento (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  rio text not null,
  localidade text not null,
  lat numeric,
  lng numeric,
  codigo_ana text,
  cota_atencao_cm integer,
  cota_alerta_cm integer,
  cota_emergencia_cm integer,
  ativa boolean not null default true,
  created_at timestamptz not null default now(),
  sentido_alerta text not null default 'cheia' check (sentido_alerta in ('cheia','seca'))
);

alter table estacoes_monitoramento enable row level security;
create policy estacoes_monitoramento_select on estacoes_monitoramento for select to authenticated using (true);
create policy estacoes_monitoramento_insert on estacoes_monitoramento for insert to authenticated with check (pode_escrever());
create policy estacoes_monitoramento_update on estacoes_monitoramento for update to authenticated using (pode_escrever()) with check (pode_escrever());
create policy estacoes_monitoramento_delete on estacoes_monitoramento for delete to authenticated using (pode_escrever());

-- ============================================================
-- MONITORAMENTO AMBIENTAL — REGISTROS
-- ============================================================
create table if not exists registros_nivel (
  id uuid primary key default gen_random_uuid(),
  estacao_id uuid not null references estacoes_monitoramento(id),
  data date not null,
  cota_cm integer not null,
  fonte text not null default 'manual' check (fonte in ('manual','ana','mamiraua')),
  responsavel text,
  observacoes text,
  created_at timestamptz not null default now(),
  situacao_tendencia text
    check (situacao_tendencia in ('estiagem','vazante','estavel','enchendo','cheia')),
  unique (estacao_id, data, fonte)
);

alter table registros_nivel enable row level security;
create policy registros_nivel_select on registros_nivel for select to authenticated using (true);
create policy registros_nivel_insert on registros_nivel for insert to authenticated with check (pode_escrever());
create policy registros_nivel_update on registros_nivel for update to authenticated using (pode_escrever()) with check (pode_escrever());
create policy registros_nivel_delete on registros_nivel for delete to authenticated using (pode_escrever());

create table if not exists registros_clima (
  id uuid primary key default gen_random_uuid(),
  estacao_id uuid not null references estacoes_monitoramento(id),
  data date not null,
  variavel text not null,
  valor numeric not null,
  unidade text,
  fonte text not null default 'openmeteo',
  created_at timestamptz not null default now(),
  unique (estacao_id, data, variavel, fonte)
);

alter table registros_clima enable row level security;
create policy registros_clima_select on registros_clima for select to authenticated using (true);
create policy registros_clima_insert on registros_clima for insert to authenticated with check (pode_escrever());
create policy registros_clima_update on registros_clima for update to authenticated using (pode_escrever()) with check (pode_escrever());
create policy registros_clima_delete on registros_clima for delete to authenticated using (pode_escrever());

create table if not exists registros_umidade (
  id uuid primary key default gen_random_uuid(),
  estacao_id uuid not null references estacoes_monitoramento(id),
  data date not null,
  umidade_pct numeric not null,
  fonte text not null default 'manual' check (fonte in ('manual','inmet','openmeteo')),
  responsavel text,
  observacoes text,
  created_at timestamptz not null default now(),
  unique (estacao_id, data, fonte)
);

alter table registros_umidade enable row level security;
create policy registros_umidade_select on registros_umidade for select to authenticated using (true);
create policy registros_umidade_insert on registros_umidade for insert to authenticated with check (pode_escrever());
create policy registros_umidade_update on registros_umidade for update to authenticated using (pode_escrever()) with check (pode_escrever());
create policy registros_umidade_delete on registros_umidade for delete to authenticated using (pode_escrever());

create table if not exists registros_chuva (
  id uuid primary key default gen_random_uuid(),
  estacao_id uuid not null references estacoes_monitoramento(id),
  data date not null,
  chuva_mm numeric not null,
  fonte text not null default 'manual' check (fonte in ('manual','ana','inmet')),
  responsavel text,
  observacoes text,
  created_at timestamptz not null default now(),
  unique (estacao_id, data, fonte)
);

alter table registros_chuva enable row level security;
create policy registros_chuva_select on registros_chuva for select to authenticated using (true);
create policy registros_chuva_insert on registros_chuva for insert to authenticated with check (pode_escrever());
create policy registros_chuva_update on registros_chuva for update to authenticated using (pode_escrever()) with check (pode_escrever());
create policy registros_chuva_delete on registros_chuva for delete to authenticated using (pode_escrever());

create table if not exists limiares_clima (
  id uuid primary key default gen_random_uuid(),
  estacao_id uuid not null references estacoes_monitoramento(id),
  variavel text not null,
  sentido text not null default 'alta' check (sentido in ('alta','baixa')),
  atencao numeric,
  alerta numeric,
  emergencia numeric,
  created_at timestamptz not null default now(),
  unique (estacao_id, variavel)
);

alter table limiares_clima enable row level security;
create policy limiares_clima_select on limiares_clima for select to authenticated using (true);
create policy limiares_clima_insert on limiares_clima for insert to authenticated with check (pode_escrever());
create policy limiares_clima_update on limiares_clima for update to authenticated using (pode_escrever()) with check (pode_escrever());
create policy limiares_clima_delete on limiares_clima for delete to authenticated using (pode_escrever());

-- ============================================================
-- FOCOS DE CALOR (histórico coletado pelo robô focos-sync)
-- ============================================================
create table if not exists focos_historico (
  id bigint generated by default as identity primary key,
  chave text not null unique,
  lat double precision not null,
  lon double precision not null,
  data_hora text,
  data_foco date,
  satelite text,
  municipio text,
  estado text,
  risco_fogo double precision,
  frp double precision,
  bioma text,
  registrado_em timestamptz not null default now()
);

alter table focos_historico enable row level security;
create policy focos_historico_select on focos_historico for select to authenticated using (true);
create policy focos_historico_insert on focos_historico for insert to authenticated with check (pode_escrever());
create policy focos_historico_update on focos_historico for update to authenticated using (pode_escrever()) with check (pode_escrever());
create policy focos_historico_delete on focos_historico for delete to authenticated using (pode_escrever());
